const MAX=25*1024*1024,$=s=>document.querySelector(s),e={drop:$('#dropZone'),input:$('#fileInput'),editor:$('#editor'),original:$('#originalImage'),canvas:$('#resultCanvas'),name:$('#fileName'),meta:$('#fileMeta'),status:$('#status'),process:$('#processBtn'),download:$('#downloadBtn'),newFile:$('#newFile'),range:$('#compareRange'),layer:$('#resultLayer'),divider:$('#divider')};
// Profil alpha Gemini compact (24×24), adapté d'un projet MIT puis interpolé à la taille détectée.
const A='AQAAAQAAAQEBAQFFRAEBAQEBAgEBAgMBAQAAAQECAQEBAQFucAEBAQIBAwECAgECAQAAAQEBAAAAAByAgCABAQIBAQMDAQEBAAABAgEAAgEBAViAgFgBAAECAQIBAQEBAQEBAQEBAQEBIYCAgIAhAQEBAgMDAgECAQABAQEBAQIEcICAgIBsBgICAgECAQIBAQEAAQEBAQFagICAgICAVgEBAQIBAgICAQEBAAAAAUmAgICAgICAgEgBAQIBAQIBAQEBAQAGVoCAgYCAgICAgIBaBgEBAwIBAQEAASBsgICAgICAgICAgICAcSEDAgIBAQAgWICAgICAgICAgICAgICAgIBYHQIBRHCAgICAgICAgICAgICAgICAgICAgG5FRG6AgICAgICAgICAgICAgICAgICAgHBEAQEdWICAgICAgICAgICAgICAgIBZIQIBAQEAASBwgICAgICAgICAgICAbSEBAQEBAQEBAAEEWoCAgICAgICAgIBWBwECAQIBAQEBAQAAAUiAgIGAgICBgEgEAgIBAwIBAQIBAwICAQFXgICAgICAWgIDAQICAwEDAgICAQICAgEIbICAgIBwBQIAAQMCAAEBAgEBAQEBAQICIICAgIAhAQIBAQEBAQEBAQEBAQIAAQIBAViAgFgBAQIBAQEBAgEBAgICAQEBAgEBAiGBgB0CAQEBAgEBAQIBAgIBAgEBAgIBAgFxbgECAQIBAQEBAQIBAQECAQEBAQIBAQJERQECAgEBAgECAQIB';
let file,url,alpha;
function msg(t,c=''){e.status.textContent=t;e.status.className=c}
function reset(){if(url)URL.revokeObjectURL(url);file=url=null;e.input.value='';e.editor.hidden=true;e.drop.hidden=false;e.download.disabled=true;msg('Image prête. Lancez l’analyse locale.')}
async function load(f){if(!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type))return alert('Choisissez un fichier PNG, JPG ou WebP.');if(f.size>MAX)return alert('Cette image dépasse 25 Mo.');reset();file=f;url=URL.createObjectURL(f);e.original.src=url;await e.original.decode();e.canvas.width=e.original.naturalWidth;e.canvas.height=e.original.naturalHeight;e.canvas.getContext('2d').drawImage(e.original,0,0);e.name.textContent=f.name;e.meta.textContent=`${e.canvas.width} × ${e.canvas.height} px · ${(f.size/1048576).toFixed(2)} Mo`;e.drop.hidden=true;e.editor.hidden=false}
function profile(){if(alpha)return alpha;if(window.GEMINI_ALPHA_48_BASE64){const raw=Uint8Array.from(atob(window.GEMINI_ALPHA_48_BASE64),c=>c.charCodeAt(0)),view=new DataView(raw.buffer);return alpha=Float32Array.from({length:2304},(_,i)=>view.getFloat32(i*4,true))}return alpha=Float32Array.from(atob(A),c=>c.charCodeAt(0)/255)}
function sample(a,x,y,size){const side=Math.round(Math.sqrt(a.length)),sx=(x+.5)*side/size-.5,sy=(y+.5)*side/size-.5,x0=Math.max(0,Math.min(side-1,Math.floor(sx))),y0=Math.max(0,Math.min(side-1,Math.floor(sy))),x1=Math.min(side-1,x0+1),y1=Math.min(side-1,y0+1),tx=Math.max(0,sx-x0),ty=Math.max(0,sy-y0),top=a[y0*side+x0]*(1-tx)+a[y0*side+x1]*tx,bottom=a[y1*side+x0]*(1-tx)+a[y1*side+x1]*tx;return top*(1-ty)+bottom*ty}
function geometry(w,h){if(w===768&&Math.abs(h-1376)<=1)return{size:48,mr:32,mb:32,name:'Gemini 1K'};const ratio=h/w;if(w>=700&&w<=1300&&ratio>1.76&&ratio<1.82)return{size:Math.round(w/16),mr:Math.round(w/24),mb:Math.round(w/24),name:'Gemini 1K redimensionné'};return null}
function evidence(img,g,a){const{x=0}=g,w=img.width,h=img.height,ox=w-g.mr-g.size,oy=h-g.mb-g.size;let core=0,bg=0,nc=0,nb=0;for(let y=0;y<g.size;y+=2)for(let x=0;x<g.size;x+=2){const al=sample(a,x,y,g.size),i=((oy+y)*w+ox+x)*4,l=(img.data[i]+img.data[i+1]+img.data[i+2])/3;if(al>.08){core+=l;nc++}else if(al<.015){bg+=l;nb++}}return core/Math.max(1,nc)-bg/Math.max(1,nb)}
function restore(ctx,w,h){const g=geometry(w,h);if(!g)return null;const a=profile(),img=ctx.getImageData(0,0,w,h),score=evidence(img,g,a);if(!Number.isFinite(score)||score<2.5)return null;const ox=w-g.mr-g.size,oy=h-g.mb-g.size,gain=score>90?1.45:1;for(let y=0;y<g.size;y++)for(let x=0;x<g.size;x++){const al=sample(a,x,y,g.size);if(al<.012)continue;const safe=Math.min(al*gain,.92),i=((oy+y)*w+ox+x)*4;for(let c=0;c<3;c++)img.data[i+c]=Math.max(0,Math.min(255,Math.round((img.data[i+c]-safe*255)/(1-safe))))}ctx.putImageData(img,0,0);return{...g,score,gain}}
async function process(){e.process.disabled=true;e.download.disabled=true;msg('Analyse locale de la zone Gemini…');await new Promise(r=>setTimeout(r,50));const ctx=e.canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(e.original,0,0);const result=restore(ctx,e.canvas.width,e.canvas.height);if(!result){msg('Aucune marque Gemini compatible reconnue. L’original reste intact.','error');ctx.drawImage(e.original,0,0)}else{msg(`Marque restaurée localement · profil ${result.name}. Vérifiez le résultat.`,'success');e.download.disabled=false}e.process.disabled=false}
e.drop.onclick=()=>e.input.click();e.drop.onkeydown=x=>{if(x.key==='Enter'||x.key===' '){x.preventDefault();e.input.click()}};e.input.onchange=()=>load(e.input.files[0]);['dragenter','dragover'].forEach(t=>e.drop.addEventListener(t,x=>{x.preventDefault();e.drop.classList.add('drag')}));['dragleave','drop'].forEach(t=>e.drop.addEventListener(t,x=>{x.preventDefault();e.drop.classList.remove('drag')}));e.drop.ondrop=x=>load(x.dataTransfer.files[0]);e.newFile.onclick=reset;e.process.onclick=process;e.range.oninput=()=>{e.layer.style.clipPath=`inset(0 0 0 ${e.range.value}%)`;e.divider.style.left=e.range.value+'%'};e.download.onclick=()=>e.canvas.toBlob(b=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=file.name.replace(/\.[^.]+$/,'')+'-clean.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},'image/png');
